import type {
	CameraBrands,
	Config,
	ImagesConfigItem,
	Img,
	WatermarkListBaseItem,
	WatermarkListItem,
} from "../types";
import { useStore } from "../stores";

export const print = (config: Config, img: Img) => {
	console.log("当前配置：", config);
	console.log("当前图片信息：", img);
};

// 定义相机品牌
export const cameraBrands: CameraBrands[] = [
	{
		name: "佳能(圆)",
		logo: "canon-circle",
		make: ["Canon"],
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMSaEwVCWJ_jB9NWK0UAm1U3eB1EEsAAjzMMRuHymFWdfcfYFNCmlABAAMCAAN5AAM2BA.png",
	},
	{
		name: "佳能",
		logo: "canon",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMcaEwcgAABOGyKi_uwmPMeIUpdI1PcAAKhxDEbh8ppVv8B2VpqpmVdAQADAgADeQADNgQ.png",
	},
	{
		name: "签名1",
		logo: "sign1",
		url: "https://s21.ax1x.com/2025/10/08/pVHCljA.png",
	},
	{
		name: "签名2",
		logo: "sign2",
		url: "https://s21.ax1x.com/2025/10/09/pVHC8Bt.png",
	},
	{
		name: "文字-1",
		logo: "text-1",
		url: "https://s21.ax1x.com/2025/10/09/pVHeW80.png",
	},
	{
		name: "文字-2",
		logo: "text-2",
		url: "https://s21.ax1x.com/2025/10/09/pVHeob4.png",
	},
	// {
	// 	name: "佳能(白)",
	// 	logo: "canon-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMeaEwcwjof7uGTnjFF2YuTD1Z0x-AAAqPEMRuHymlWLlMQEc-wPyYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "佳能-2",
	// 	logo: "canon-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMdaEwcr866xCb84D6bPA90nNaoPxAAAqLEMRuHymlWZ8ZxRTbmNW8BAAMCAAN5AAM2BA.png",
	// },
	{
		name: "尼康",
		logo: "nikon",
		make: ["NIKON CORPORATION"],
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANIaEwiv-eggtEiZVVeNyoqZ9IT7QwAAuDIMRvPAWFWD_DCJqPVvH4BAAMCAAN5AAM2BA.png",
	},
	// {
	// 	name: "尼康-文字(黑)",
	// 	logo: "nikon-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANJaEwi2GnyUxMQ0_-d8ze5EknUUjQAAuHIMRvPAWFWPSvn2HOio-EBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "尼康-文字(白)",
	// 	logo: "nikon-2-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANKaEwi6I3bTgrdhMBAShb-OvdzhmwAAuLIMRvPAWFWKRnv2yqb6ocBAAMCAAN5AAM2BA.png",
	// },
	{
		name: "索尼(黑)",
		logo: "sony",
		make: ["SONY"],
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANkaEwmaayv-YXWIgqkAxh8UJChQA0AAobJMRvPAWFWvJ_u2AO_mhYBAAMCAAN5AAM2BA.png",
	},
	{
		name: "索尼(白)",
		logo: "sony-white",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANpaEwnFLmLoDgq0EzxQJbFOPmLIT0AAo7JMRvPAWFWdUbpXmmcZiMBAAMCAAN5AAM2BA.png",
	},
	// {
	// 	name: "索尼-Alpha(白)",
	// 	logo: "sony-alpha-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANoaEwm_xC0u9x7StWlihQkGdj8kSUAAo3JMRvPAWFW8pzPC1opLBABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "索尼-Alpha(黑)",
	// 	logo: "sony-alpha-black",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANnaEwm5q4ZlETNhdbEIwnyQhTkPRwAAozJMRvPAWFWkWHoa_oN-2ABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "索尼-Alpha2(黑)",
	// 	logo: "sony-alpha-2-black",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANlaEwmi65m7MTnlbYiNKIKLw1ooZUAAm_DMRsIRGBWzXO1dvclkbgBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "索尼-Alpha2(白)",
	// 	logo: "sony-alpha-2-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANmaEwmnjzotzZ8WeGhlzkFq7w_2P0AAorJMRvPAWFW3_NDo3Z5y0ABAAMCAAN4AAM2BA.png",
	// },
	{
		name: "富士",
		logo: "fuji",
		make: ["FUJIFILM"],
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMnaEweO0HODB1cTAy_4VvcNzEwBMwAArPIMRvPAWFW_eVwUdGtstcBAAMCAAN5AAM2BA.png",
	},
	{
		name: "富士(白)",
		logo: "fuji-white",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMoaEwediXiejCR9w9rwz5N1MTJfecAArXIMRvPAWFWVKXSvXtpbSQBAAMCAAN5AAM2BA.png",
	},
	{
		name: "松下",
		logo: "panasonic",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANWaEwkYuuCUGuUCWm-3g3NVmkzFAMAAvLIMRvPAWFWweRf6Wrp2UMBAAMCAAN5AAM2BA.png",
	},
	{
		name: "Lumix",
		logo: "lumix",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANCaEwgyxRHzkq0Wy8k49i7RH3SkaoAAtjIMRvPAWFWRqkstF2oQ7YBAAMCAAN5AAM2BA.png",
	},
	{
		name: "Lumix(白)",
		logo: "lumix-white",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANDaEwhTCo0eIU60Zq27ZNinNV5aGoAAtnIMRvPAWFWQuUxoWr-4WIBAAMCAAN5AAM2BA.png",
	},
	{
		name: "小米",
		logo: "xiaomi",
		make: ["Xiaomi"],
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANzaEwocebyRbK_Nnjg9TUc1t3u4I8AAp3JMRvPAWFWUKCKFCNGbV4BAAMCAAN5AAM2BA.png",
	},
	{
		name: "小米-2",
		logo: "xiaomi-2",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN0aEwohM_q-OrV3py249HZXraCfEgAAp7JMRvPAWFWQU1ippfuCikBAAMCAANtAAM2BA.png",
	},
	{
		name: "小米-文本",
		logo: "xiaomi-text",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN2aEwonV2FKz9aZX400jCab67vqNoAAqDJMRvPAWFW5debyGa1M9oBAAMCAAN4AAM2BA.png",
	},
	{
		name: "小米-文本(白)",
		logo: "xiaomi-text-white",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN3aEwoqkvrYVK_Z1Joc9tUQWAGVAMAAqHJMRvPAWFWcOn4TVC0txcBAAMCAAN4AAM2BA.png",
	},
	// {
	// 	name: "小米汽车",
	// 	logo: "xiaomi-car",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN1aEwokc_nz2VBWms0ZfTvPpT-hqQAAp_JMRvPAWFWBpOMzjZQ6BEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "小米澎湃",
	// 	logo: "hyperos",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM0aEwfb45UjenAnf9yCDWJWkEubIoAAsXIMRvPAWFWNkigTPnNHKABAAMCAAN5AAM2BA.png",
	// },
	{
		name: "红米(彩色)",
		logo: "redmi",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANeaEwlnhcKIeoOUI1hDO-9x099JKEAAnvJMRvPAWFWTfzyfcv7sa4BAAMCAAN5AAM2BA.png",
	},
	// {
	// 	name: "红米(黑)",
	// 	logo: "redmi-black",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANfaEwlso2_SdS_T4j7gljonQFjXesAAnzJMRvPAWFW-pwWQpSF2QsBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "红米(白)",
	// 	logo: "redmi-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANgaEwl7PzWcocvBg29FgjEItXDSlEAAoDJMRvPAWFW7FXy9PsuQAcBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "华为",
	// 	logo: "huawei",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMxaEwfKXME2MJG9bKDgojy6ptkVqUAAsDIMRvPAWFWFXFom_hHCCsBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "XMAGE-2",
	// 	logo: "xmage-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN5aEwo1BxapWrzZU_wsceiCPTksS4AAqPJMRvPAWFWwCtB3kD5w4IBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "XMAGE",
	// 	logo: "xmage",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN4aEwoxdYqjxCmzAm7O7G3b8n81a8AAhfGMRs7YWBW4Nm-Lm_Kje4BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "华为(黑)",
	// 	logo: "huawei-black",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMyaEwfUjLMkLyIlMHwvk94Xylq6JIAAsLIMRvPAWFW4Sk6W5N9zosBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "华为(白)",
	// 	logo: "huawei-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMzaEwfXxZcmWYlAnnOOR1clrA6YroAAsTIMRvPAWFWzuLW_BVGRQgBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "荣耀",
	// 	logo: "honor",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMvaEwfBqr9CKShtT7lpWZvJzMBcc0AArzIMRvPAWFWKcDeRwwAAdehAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "苹果(黑)",
	// 	logo: "apple",
	// 	make: ["Apple"],
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMTaEwbUeTy-mvMMaOawfA4BCevYeEAApfEMRuHymlWc-vEQqIdiIEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "苹果(灰)",
	// 	logo: "apple-gray",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMUaEwbc-sZDSS-nnEZLQx-vB-tD4UAApnEMRuHymlWvAABTbrFxzUTAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "苹果(白)",
	// 	logo: "apple-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMVaEwbheDFRHhzwN_Xgv1mMSJf5tAAAprEMRuHymlWsrHR-aYB4MABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "OPPO",
	// 	logo: "oppo",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANVaEwkSRpGuM9XaL3QD0WvL1l_JXQAAvHIMRvPAWFWn5xh46ZFIGkBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "一加",
	// 	logo: "oneplus",
	// 	make: ["OnePlus"],
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANRaEwjkDeu2qVrmq4g-CudxsHEswgAAurIMRvPAWFWMBkvMfaz4pYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "一加(黑)",
	// 	logo: "oneplus-black",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANSaEwjozHnRJQeQMPlmehJuu3SVaAAAuvIMRvPAWFW9WWhG9lBvsEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "一加(白)",
	// 	logo: "oneplus-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANUaEwjzJR5Ixb_HREi-ZfPh9JLxHgAAu7IMRvPAWFWBu_YVepBsKsBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "一加(红)",
	// 	logo: "oneplus-red",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANTaEwjt8PTWbtp66ccJAABVLL5NlYWAALsyDEbzwFhVjod7enZOXCqAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "vivo",
	// 	logo: "vivo",
	// 	make: ["vivo"],
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANtaEwnjD5AfPeWFH4cc7nEWDcZv34AApLJMRvPAWFWiIMQh3MaRNsBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "vivo-文字(黑)",
	// 	logo: "vivo-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANuaEwn3KIrosTFbsYR3XatVqltkVMAApPJMRvPAWFWF0-ELHbu2vEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "vivo-文字(白)",
	// 	logo: "vivo-2-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANvaEwn9YasyuFsqU5bNroPiuXOSEEAApTJMRvPAWFWnW_W5UeMcKUBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "IQOO",
	// 	logo: "iqoo",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM1aEwffLdEjgugYmD1dbf1yLbrEAsAAsbIMRvPAWFWzwIm6EhFWSMBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "IQOO-2",
	// 	logo: "iqoo-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM2aEwfjEwC9hHW0mPCtfqexMp-608AAsfIMRvPAWFWBTm-JHcxMyEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "真我",
	// 	logo: "realme",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANcaEwlQ2vn-bmV7cxD8Y2aWCF_sb0AAnfJMRvPAWFWAAEBVpVz88RDAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "真我-2",
	// 	logo: "realme-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANdaEwljN4gYrgXfTpCboxnHi6TM9cAAnrJMRvPAWFW8GBz75wRluQBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "努比亚",
	// 	logo: "nubia",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANPaEwjYZRNJqv5QJATyq6aOyJFMDUAAufIMRvPAWFWRPZ1nu47aJ4BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "适马",
	// 	logo: "sigma",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANjaEwmVhwOzwz7NiBbPGyOA7DwfY4AAoXJMRvPAWFWPyT4SF_FaIUBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "徕卡",
	// 	logo: "leica",
	// 	make: ["LEICA CAMERA AG"],
	// 	url: "https://s21.ax1x.com/2025/06/13/pVAlBin.png",
	// 	// url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMSaEwVCWJ_jB9NWK0UAm1U3eB1EEsAAjzMMRuHymFWdfcfYFNCmlABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "哈苏(黑)",
	// 	logo: "hasselblad",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMraEweutl33sxtB-SvXbysDiFK-n8AArjIMRvPAWFW4XC9rh41BI8BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "哈苏(白)",
	// 	logo: "hasselblad-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMuaEwe9omYoWWiZb6d11u4P5Sus74AArvIMRvPAWFWcktvPBdWoCEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "哈苏-2(黑)",
	// 	logo: "hasselblad-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMsaEwe0iBRVSaA1V8z6YOry_vC5fgAArnIMRvPAWFWk-bYDakuRlcBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "哈苏-2(白)",
	// 	logo: "hasselblad-2-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMtaEwe5HcchppXMnUrfrAoJqcj03YAArrIMRvPAWFWTk-L46i-4SABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "大疆",
	// 	logo: "dji",
	// 	make: ["DJI"],
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMkaEwdwVRV3-OCPPF5ge-UeO4qHP0AAq_IMRvPAWFWgkpquZSKNcoBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "大疆(白)",
	// 	logo: "dji-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMlaEweFNXf_k1OY5R58GZat-OtwUEAArDIMRvPAWFWBEa8S9hOmo4BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "蔡司",
	// 	logo: "zeiss",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAOBaEwp2G1Bp-_CdLf8EiGLT-TIvXoAAqrJMRvPAWFWbaj89Z0HVsYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "奥林巴斯",
	// 	logo: "olympus",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANQaEwjeCXfmwSgFMmwlgZ37zqRIYsAAujIMRvPAWFWiFWAmCHf6EEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "诺基亚(新)",
	// 	logo: "nokia",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANNaEwjMtKkheeiYAiWDV5yCTp7ngkAAuXIMRvPAWFWikuSgeQm74sBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "诺基亚",
	// 	logo: "nokia-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANOaEwjRyvhEj9WN1OJxNGjOWD0flYAAubIMRvPAWFWddeuzlXTsBYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "酷派",
	// 	logo: "coolpad",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMiaEwdUQAB38p2glhJh5hUP80x1vv5AAKtyDEbzwFhVoVTL7v_0x0dAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "酷派-2",
	// 	logo: "coolpad-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMjaEwdZmZmT6DseSay04-KT1eDqiUAAq7IMRvPAWFWX_VDENlZc-ABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "联想",
	// 	logo: "lenvo",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM-aEwgO4_vNugdwI_-cXo0Wg4pL64AAtLIMRvPAWFWLWfu0SGngJ8BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "柯达",
	// 	logo: "kodak",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM7aEwf1sxElsMZM26eIEpZISX2BXUAAtDIMRvPAWFWHHK53EQgmfEBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "柯达-透明",
	// 	logo: "kodak-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM8aEwgB1X5XMxpyRaiHcE6xXD24mQAAtHIMRvPAWFW07Ueth7i4MABAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "央视新闻",
	// 	logo: "ysxw",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN9aEwpk6aTszjQgAQCJLhR2xgVRUIAAqbJMRvPAWFW7OxveIw69ScBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "中国国家地理(黑)",
	// 	logo: "cng",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMgaEwdL6ARWtPViwvhzmsDyyAjELcAAqvIMRvPAWFWHneFJboCFYkBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "中国国家地理(白)",
	// 	logo: "cng-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMhaEwdQWBeQmXnnKl36OVMUgQwvTsAAqzIMRvPAWFWP3oePYH-9aUBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "视觉中国(黑)",
	// 	logo: "vcg",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANraEwnbeYYz0Lk4mCNwm6gxZGK7MsAApDJMRvPAWFWO_25lA-WR4cBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "视觉中国(白)",
	// 	logo: "vcg-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANsaEwngmuhleXqsWBkVMI22trb4i8AApHJMRvPAWFW54soE8KHge4BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Photoshop",
	// 	logo: "ps",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANZaEwksv14mcoNuAHyTny37sJuPlcAAvbIMRvPAWFWFTHwOF8JM00BAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "Lightroom",
	// 	logo: "lightroom",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM_aEwgU2P5aTYJYj_RYN_TO0GhtgkAAtXIMRvPAWFW56-yIJeh-jEBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "像素蛋糕",
	// 	logo: "xsdg",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN6aEwpKcgOfeGrw1hCHkXs9QdNDuYAAqTJMRvPAWFWtcYl-Vhegd8BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "像素蛋糕-2",
	// 	logo: "xsdg-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN7aEwpVXJ7xE4tFug5RsdDYebXfOcAAqXJMRvPAWFWKmHvXCc8HOEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Google",
	// 	logo: "google",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMpaEweiBZKGTyYSpA8pw0Z7lHWEgIAArbIMRvPAWFWZtwmU8KNdzgBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Google-2",
	// 	logo: "google-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMqaEweq8OrxdAdtYzn7v29eqeCNA4AArfIMRvPAWFWvhjDcMKLCpYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Samsung",
	// 	logo: "samsung",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANhaEwmMnie6V_RJmGKK4qBSe1GSQQAAoPJMRvPAWFWPZRLRfX156oBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Samsung-2",
	// 	logo: "samsung-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANiaEwmSLmtZbhCJReaGcMWjZF3JvgAAoTJMRvPAWFWzq-E022dSQABAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "Microsoft",
	// 	logo: "microsoft",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANFaEwiWaPXrJhJLPbmO74FisHH3nkAAtzIMRvPAWFWB28sPu4HBUoBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Microsoft-2",
	// 	logo: "microsoft-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANGaEwim_XZ1IGXGEzbfAjGqq462OIAAt3IMRvPAWFWROWBVylGo2oBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Windows11",
	// 	logo: "windows11",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANwaEwoPwH0cmSk2kRMzo074UXSnj0AAprJMRvPAWFWRcBQjwSXTn8BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "WindowsXp",
	// 	logo: "windows-xp",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANxaEwoVcR2S1_JSGI-cmVhF7OAf2wAApvJMRvPAWFW4BrjnLcf5oABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "CCTV",
	// 	logo: "cctv",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMfaEwdAnJe87IcYXnOLRoV4cg8kTIAAqrIMRvPAWFW9OKBJTyPfhgBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "BBC",
	// 	logo: "bbc",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMaaEwcUliEQWe7SThnYi9lL3JkgQYAAp_EMRuHymlWPi-hYQMC8-0BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "抖音",
	// 	logo: "douyin",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMmaEweJ6hbeoL8zEbDNVGG80sr0CUAArLIMRvPAWFWzZxHoJZ0MNwBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "小红书",
	// 	logo: "xhs",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANyaEwoYCNh-edEZffx9zY7nyVJS9UAApzJMRvPAWFWpwwOxVrx94cBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "QQ",
	// 	logo: "qq",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANaaEwk3uYh_u8nbyfu1gqjwYCj_EMAAvfIMRvPAWFWJh0Ft6FO0OgBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "QQ空间",
	// 	logo: "qzone",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANbaEwlMduBZBE_InEIL-JkmxlrVEsAAnPJMRvPAWFWCRBEKON-vzQBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Java",
	// 	logo: "java",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM3aEwfmVimC-e6_7rWchBK1jzIKwMAAsjIMRvPAWFWMCYE1W4z-N8BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "Javascript",
	// 	logo: "javascript",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM4aEwfqqThmjRd9jcupxceLeqgec8AAsrIMRvPAWFWsjqvwmErMlUBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "nodejs",
	// 	logo: "nodejs",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANMaEwjF-cf2QsVzBXNZAbSHB4-mPgAAuTIMRvPAWFWlhTF6_w39aMBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "PHP",
	// 	logo: "php",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANYaEwknyYAAU4wrWd2c6QnxZBeT61gAAL0yDEbzwFhViLPst1aCufSAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "耐克",
	// 	logo: "nike",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANHaEwiqhNAokQ7oTm0XyKw8_2XMXwAAt_IMRvPAWFWqi77XCnwNLYBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "南极人",
	// 	logo: "njr",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANLaEwi_C3VWQUlYCCMou6XZnJ9DpYAAuPIMRvPAWFWIbmDCWDYF5YBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "拼多多",
	// 	logo: "pdd",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANXaEwkjCyHBjRH3r_-PQV9GN2tfEkAAvPIMRvPAWFWKwiw1IQofzABAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "菠萝",
	// 	logo: "boluo",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMbaEwcZQ-x5E1m-SEVUnghqi3XrXcAAqDEMRuHymlWuCAef-7LP1UBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "和平精英",
	// 	logo: "hpjy",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMwaEwfG52Nq6vOxta5whed_M2-BUYAAr3IMRvPAWFWolqepGkcMtEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "原神",
	// 	logo: "yuanshen",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN-aEwpsn226wG1mA55Z6JhPgs2bBQAAqfJMRvPAWFWHoRu0ZjlaPUBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "原神-2",
	// 	logo: "yuanshen-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAN_aEwpw0gu9LqE8qCYUeGBP91At7sAAqjJMRvPAWFWdgk9AAHn9PPTAQADAgADeQADNgQ.png",
	// },
	// {
	// 	name: "原神-2(白)",
	// 	logo: "yuanshen-2-white",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAOAaEwpzvVs-_3_VXRzMH7MfaYMd9kAAqnJMRvPAWFW5qw5vWsa-3sBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "瑞幸",
	// 	logo: "luckin",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANBaEwgtJEsAc9BZZYRunSxx4z0mggAAtfIMRvPAWFWb68uQd7dVn4BAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "星巴克",
	// 	logo: "starbucks",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANqaEwnQkCDFmui5tWtU-bz27VyD_IAAo_JMRvPAWFW6jIop_QxcJgBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "KFC",
	// 	logo: "kfc",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM5aEwfunD8Seb7c89CRoWYJjdjdB8AAs7IMRvPAWFWXQ9H3fLO8YEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "KFC-2",
	// 	logo: "kfc-2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAM5aEwfunD8Seb7c89CRoWYJjdjdB8AAs7IMRvPAWFWXQ9H3fLO8YEBAAMCAAN5AAM2BA.png",
	// },
	// {
	// 	name: "麦当劳",
	// 	logo: "mcd",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAANEaEwhi4sEvM_vbgUvCoXJfvDye9kAAtrIMRvPAWFWxb36uQRsjXcBAAMCAAN5AAM2BA.png",
	// },
	{
		name: "头像1",
		logo: "avatar1",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMWaEwbvu8MA0-8EybFVXNJlPH_wEwAApvEMRuHymlWOsCz1Qho2xIBAAMCAAN3AAM2BA.png",
	},
	// {
	// 	name: "头像2",
	// 	logo: "avatar2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMXaEwbzS98JYHmT2Lx8P1i22UFfEYAApzEMRuHymlWyvRIsOSSKSEBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "头像3",
	// 	logo: "avatar3",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMYaEwcLv7I8tT2lEUiMBT-0joaRaMAAp3EMRuHymlWQ7KFD_t3udEBAAMCAAN4AAM2BA.png",
	// },
	// {
	// 	name: "头像4",
	// 	logo: "avatar4",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMZaEwcPot69qPChvykxrtqc0RXmwEAAp7EMRuHymlW2NsAAbqTLWOXAQADAgADeAADNgQ.png",
	// },
];

export const watermarkList: WatermarkListBaseItem[] = [
	{
		name: "小米徕卡",
		config: "小米徕卡",
		url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMEZ_5rRw5CVPpsGb88YlmJczm3178AAn3DMRs4AAH4V7vXffdQ9OpZAQADAgADdwADNgQ.jpeg",
	},
	{
		name: "小米徕卡3",
		config: "小米徕卡3",
		url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMRaEr1wmrgpNOyv3yr9p4ahx_SGu8AAm0WAAKHyllWJ0IWgzCtAv42BA.jpeg",
	},
	{
		name: "样式1",
		config: "样式1",
		url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMRaEr1wmrgpNOyv3yr9p4ahx_SGu8AAm0WAAKHyllWJ0IWgzCtAv42BA.jpeg",
	},
	{
		name: "样式2",
		config: "样式2",
		url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMRaEr1wmrgpNOyv3yr9p4ahx_SGu8AAm0WAAKHyllWJ0IWgzCtAv42BA.jpeg",
	},
	// {
	// 	name: "Lumix",
	// 	config: "Lumix",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMPaAjt_05QYVvgKJltAhWbbFX3QXkAAp3NMRvi30hUEZeq9yNUbYMBAAMCAAN3AAM2BA.jpeg",
	// },
	// {
	// 	name: "XMAGE",
	// 	config: "XMAGE",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMOaAMgQ-9qLslbLbeaPWsrN8vc0S8AAgnGMRuH_RlUBHf9LifJp8oBAAMCAAN3AAM2BA.jpeg",
	// },
	// {
	// 	name: "小米徕卡2",
	// 	config: "小米徕卡2",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMFZ_5sF_T-Bl3s1eS_0L_y4iPZEqIAAoDDMRs4AAH4VzQEPoriSRGGAQADAgADdwADNgQ.jpeg",
	// },
	// {
	// 	name: "蔡司水印",
	// 	config: "蔡司水印",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMGZ_5sKIzBgYwoCj_7vnyIREeKaAwAAoHDMRs4AAH4V9VqnRTq_IDHAQADAgADdwADNgQ.jpeg",
	// },
	// {
	// 	name: "经典模糊",
	// 	config: "经典模糊",
	// 	url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMKZ_5sYa6xUVcMdWXFMOqRseFUCo4AAn0WAAI4AAH4V_NxgUJcVsFaNgQ.jpeg",
	// },
	// {
	// 	name: "默认样式",
	// 	config: "默认样式",
	// 	url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMHZ_5sN9t_sDqdgYjPgJnh9Yk5k2sAAnsWAAI4AAH4V5_DjmQifqsdNgQ.jpeg",
	// },
	// {
	// 	name: "纯图标",
	// 	config: "纯图标",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMIZ_5sQzG9ZlG49Or4jht-2Fb-4xwAAoLDMRs4AAH4V_-Idc9UfSNSAQADAgADdwADNgQ.jpeg",
	// },
	// {
	// 	name: "经典模式",
	// 	config: "经典模式",
	// 	url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMJZ_5sUyE_ShlkB7EWFyVhz3ptAAGfAAJ8FgACOAAB-FcmokZYpDK4yTYE.jpeg",
	// },
	// {
	// 	name: "印象毛玻璃",
	// 	config: "印象毛玻璃",
	// 	url: "https://img.lsfd.asia/file/BQACAgUAAyEGAASWuELpAAMLZ_5sdfggwZHkmAZVXkqsLs4DzAUAAn4WAAI4AAH4V7HKDo2kzJPONgQ.jpeg",
	// },
	// {
	// 	name: "时间+型号",
	// 	config: "时间+型号",
	// 	url: "https://img.lsfd.asia/file/AgACAgUAAyEGAASWuELpAAMMZ_5sg0Lc_hvP3K8OVzMuerQKaR4AAoPDMRs4AAH4V0c1EWPvf2iBAQADAgADdwADNgQ.jpeg",
	// },
];

/**
 * 获取水印列表，包含预设水印和本地自定义水印
 *
 * @returns {WatermarkListItem[]} 返回合并后的水印列表，按index属性升序排列
 *
 * @description
 * - 将预设水印列表添加index属性
 * - 获取本地存储的自定义水印并转换格式
 * - 合并预设和本地水印列表并按index排序
 */
export function getWatermarkList(): WatermarkListItem[] {
	const list: WatermarkListItem[] = watermarkList.map((item, index) => {
		return { ...item, index: index };
	});

	// 获取本地的配置
	const store = useStore();
	const localNames: WatermarkListItem[] = store.localWatermarks.map(
		(item, index) => {
			let watermark_item: WatermarkListItem = {
				index: list.length + index,
				is_local: true,
				name: item.name,
				config: JSON.stringify(item.config),
				config_name: item?.config_name,
			};
			return watermark_item;
		}
	);

	// 根据index属性升序
	return [...localNames, ...list].sort((a, b) => a.index - b.index);
}

/**
 * 获取支持的字体列表
 * @returns 返回包含所有支持字体名称的字符串数组
 * @description 返回一个包含中英文字体的数组,包括Arial、宋体等常用字体
 */
export const getSupportedFonts = (): string[] => {
	return [
		"sans-serif",
		"Arial",
		"Satisfaction.ttf",
		"SCRIPTIN.ttf",
		"Long Cang",
		"Zhi Mang Xing",
		"Liu Jian Mao Cao",
		"Ma Shan Zheng",
		"黑体",
		"微软雅黑",
		"宋体",
		"楷体",
		"隶书",
		"华文行楷",
		"Courier New",
		"书体坊安景臣钢笔行书.ttf",
		"书体坊王学勤钢笔行书.ttf",
		"书体坊硬笔行书3500.ttf",
		"书体坊赵九江钢笔楷书体.ttf",
		"书体坊赵九江钢笔行书体.ttf",
		"书体坊雪纯体3500.ttf",
		"书体坊颜体.ttf",
		"全新硬笔楷书简.ttf",
		"全新硬笔行书简.ttf",
		"八大山人毛笔字体.TTF",
		"刘德华字体2008.ttf",
		"叶根友仿刘德华字体.ttf",
		"叶根友奥运字体.ttf",
		"叶根友毛笔行书.ttf",
		"叶根友特色空心简体.ttf",
		"叶根友特色简体.ttf",
		"叶根友特隶简体.TTF",
		"叶根友疾风草书.ttf",
		"叶根友神工体.ttf",
		"叶根友空心简体.ttf",
		"叶根友签名体.ttf",
		"叶根友蚕燕隶书.ttf",
		"叶根友行书繁.ttf",
		"叶根友钢笔行书.ttf",
		"叶根友非主流手写.ttf",
		"叶根友非主流钢笔手写体.ttf",
		"叶根友风帆特色简体.ttf",
		"庞中华钢笔字体.TTF",
		"方正剪纸简体.ttf",
		"方正综艺简体.ttf",
		"李国夫手写体.TTF",
		"櫻桃小丸子字.TTF",
		"毛泽东字体.ttf",
		"米芾毛笔字体.ttf",
		"苹方黑体-中粗-简.ttf",
		"苹方黑体-中粗-繁.ttf",
		"苹方黑体-中黑-简.ttf",
		"苹方黑体-中黑-繁.ttf",
		"苹方黑体-准-简.ttf",
		"苹方黑体-准-繁.ttf",
		"苹方黑体-极细-简.ttf",
		"苹方黑体-极细-繁.ttf",
		"苹方黑体-纤细-简.ttf",
		"苹方黑体-纤细-繁.ttf",
		"苹方黑体-细-简.ttf",
		"苹方黑体-细-繁.ttf",
		"薛文轩钢笔楷体.ttf",
		"迷你简硬笔楷书体.TTF",
		"郭小语钢笔楷体.ttf",
		"Times New Roman",
		"a Theme for murder.ttf",
		"AaKaiTi-2.ttf",
		"aberatn.ttf",
		"ADKS____.TTF",
		"aescrawl.ttf",
		"aggstock.ttf",
		"akbar.ttf",
		"AllCaps.ttf",
		"ALPHMA__.TTF",
		"AMANO___.TTF",
		"AMAZB___.TTF",
		"AMAZI___.TTF",
		"amazon.ttf",
		"AMAZR___.TTF",
		"American Scribe.ttf",
		"AMETZ___.TTF",
		"ANGRYBLU.TTF",
		"Aquiline.ttf",
		"BakerScript.ttf",
		"Bambino.ttf",
		"BENBROWN.TTF",
		"be______.ttf",
		"Carpenter Script.ttf",
		"CygnetRound.ttf",
		"Daft Font.TTF",
		"dali____.ttf",
		"daniel.ttf",
		"danielbd.ttf",
		"danielbk.ttf",
		"Denise Sans.ttf",
		"dnahand.ttf",
		"DOS_____.TTF",
		"Easy Street Alt EPS.ttf",
		"Easy Street EPS Bold.ttf",
		"Easy Street EPS.ttf",
		"Elegant.ttf",
		"emaustin.ttf",
		"espek___.ttf",
		"FAIL____.TTF",
		"fawn.ttf",
		"Fixogum-Mager.ttf",
		"FountainPen.ttf",
		"Friends.TTF",
		"frightnight.ttf",
		"George Gibson.ttf",
		"gesimp21.ttf",
		"hanshand.TTF",
		"Harrison.ttf",
		"HavingWrit Bold.ttf",
		"HavingWrit Heavy.ttf",
		"HavingWrit.ttf",
		"HEATHER_.TTF",
		"HenryMorganHand.ttf",
		"Herencia.ttf",
		"homework normal.TTF",
		"homework smart.TTF",
		"houstonp.ttf",
		"HYBI4___.TTF",
		"IMITD___.TTF",
		"JaneAust.ttf",
		"Jayneprint.ttf",
		"Jellofont.ttf",
		"Jennifers Hand Writing.ttf",
		"Jey.ttf",
		"Journal.ttf",
		"JPHSL.TTF",
		"Juergen Bold Kursiv.ttf",
		"Juergen Italic.ttf",
		"Juergen.ttf",
		"JUICE___.TTF",
		"JULIET__.TTF",
		"KAREH___.TTF",
		"KidsFirstPrintFont.ttf",
		"kkjwlhil.ttf",
		"LADANSE_.TTF",
		"lamarpen.ttf",
		"Lancastershire.ttf",
		"LassigueDMato.ttf",
		"LinotypeZapfino Four.ttf",
		"LinotypeZapfino Ligature.ttf",
		"LinotypeZapfino One.ttf",
		"LinotypeZapfino Three.ttf",
		"LinotypeZapfino Two.ttf",
		"lizzielongstocking.ttf",
		"Lush.ttf",
		"MA Sexy.ttf",
		"Machia.ttf",
		"Malagua.ttf",
		"Margarosa.ttf",
		"maximill.ttf",
		"ma______.ttf",
		"Missiva.ttf",
		"MKristall.ttf",
		"MLSJN.TTF",
		"Monika.TTF",
		"Nihilschiz Handwriting.ttf",
		"Old Script.ttf",
		"P22 Cezanne Regular.ttf",
		"P22 Cezanne Sketches.ttf",
		"P22 Corinthia.ttf",
		"P22 Da Vinci Backwards.ttf",
		"P22 Da Vinci Extras.ttf",
		"P22 Da Vinci Forward.ttf",
		"P22 Dearest Script.ttf",
		"P22 Dearest Swash.ttf",
		"P22 Hopper Edward.ttf",
		"P22 Hopper Josephine.ttf",
		"P22 Hopper Sketches.ttf",
		"P22 Michelangelo Extras.ttf",
		"P22 Michelangelo Regular.ttf",
		"P22 Monet Regular.ttf",
		"P22 Operina Corsivo.ttf",
		"P22 Operina Fiore.ttf",
		"P22 Rodin Extras.ttf",
		"P22 Rodin Regular.ttf",
		"P22 Vincent Extras.ttf",
		"P22 Vincent.ttf",
		"P22Broadwindsor.ttf",
		"P22Chatham.ttf",
		"P22Elizabethan.ttf",
		"P22Grenville.ttf",
		"P22Grosvenor.ttf",
		"P22Monet-Impressionist.ttf",
		"P22Monet-Sketches.ttf",
		"P22Operina-Romano.ttf",
		"P22Royalist.ttf",
		"P22Virginian.ttf",
		"P22ZanerFour.ttf",
		"P22ZanerOne.ttf",
		"P22ZanerThree.ttf",
		"P22ZanerTwo.ttf",
		"Pablo.ttf",
		"PassionsConflictROB.ttf",
		"Point-Dexter.ttf",
		"porc__.ttf",
		"Rambo Killer.ttf",
		"RegalloAPlaya.ttf",
		"Roanoke Script.ttf",
		"ROYFRG__.TTF",
		"SaginawBold.ttf",
		"SaginawLight.ttf",
		"SaginawMedium.ttf",
		"schooner.ttf",
		"SCRIPALT.ttf",
		"SF Burlington Script Bold Italic.ttf",
		"SF Burlington Script Bold.ttf",
		"SF Burlington Script Italic.ttf",
		"SF Burlington Script SC Bold Italic.ttf",
		"SF Burlington Script SC Bold.ttf",
		"SF Burlington Script SC Italic.ttf",
		"SF Burlington Script SC.ttf",
		"SF Burlington Script.ttf",
		"Shelley Allegro BT.ttf",
		"Shelley Andante BT.ttf",
		"Shelley Volante BT.ttf",
		"Sloop-ScriptOne.ttf",
		"Sloop-ScriptThree.ttf",
		"Sloop-ScriptTwo.ttf",
		"stilltim.ttf",
		"subway.TTF",
		"Sudestada Ends.ttf",
		"Sudestada.ttf",
		"Swan Song.ttf",
		"SWENSON.TTF",
		"texhero.ttf",
		"TheNautiGal ROB.ttf",
		"VIVACS.TTF",
		"WaterBrushROB.ttf",
		"Whitechapel BB.ttf",
		"Witched.TTF",
		"Write2o.ttf",
		"XinHuaKaiTi-1.ttf",
		"Yankee Ghosts BB.ttf",
		"Yelly.ttf",
		"YeZiGongChangJiaoKeShuPinYinTi-2.ttf",
		"Young Love ES.ttf",
	];
};

export const preDefineColors = [
	"#FFF",
	"#808080",
	"#CCC",
	"#DCDCDC",
	"#000",
	"#F00",
	"#00FF00",
	"#0000FF",
	"rgb(255, 213, 0)",
];
export const defaultImgValue: Img = {
	width: 0,
	height: 0,
	fileName: "",
	size: "",
	type: "",
	time: "",
	export: {
		name: "",
		quality: 0.97,
		ext: "jpeg",
	},
	exif: {},
	modelText: "",
	paramsText: "",
	timeText: "",
	lensText: "",
	locationText: "",
};

// export const defaultLabelConfig: LabelConfigItem = {
// 	name: `文本(${new Date().getTime()})`,
// 	show: true,
// 	align: "left" as TextAlign,
// 	verticalAlign: "top" as TextVerticalAlign,
// 	color: "#F00",
// 	size: 160,
// 	italic: false,
// 	bold: false,
// 	text: "请输入文本",
// 	x: 100,
// 	y: 100,
// 	font: "sans-serif",
// 	stroke: false,
// 	strokeWidth: 3,
// 	draggable: false,
// 	showRect: false,
// };

export const defaultImageConfig: ImagesConfigItem = {
	title: `自定义图片(${new Date().getTime()})`,
	show: true,
	url: "https://img-s.msn.cn/tenant/amp/entityid/BB1msyCK?w=0&h=0&q=60&m=6&f=jpg&u=t",
	horizontalOffset: 100,
	verticalOffset: 100,
	width: 300,
	height: 300,
	circle: false,
	name: "nikon",
	alpha: 1,
	rotate: 0,
	blendMode: "normal",
};

export const defaultITextConfig = {};

// export const defaultConfig: Required<Config> = {
// 	name: "默认",
// 	font: "sans-serif",
// 	paddings: {
// 		top: 0,
// 		right: 0,
// 		left: 0,
// 		bottom: 0,
// 	},
// 	watermark: {
// 		position: "bottom",
// 		height: 0,
// 		model: { ...defaultLabelConfig, enable: false, replaceZ: false },
// 		params: {
// 			...defaultLabelConfig,
// 			enable: false,
// 			useEquivalentFocalLength: true,
// 			styleIndex: 0,
// 			styles: [],
// 		},
// 		time: {
// 			...defaultLabelConfig,
// 			enable: false,
// 			format: "YYYY.MM.DD HH:mm",
// 		},
// 		lens: {
// 			...defaultLabelConfig,
// 			enable: false,
// 		},
// 		paddings: {
// 			top: 0,
// 			right: 0,
// 			left: 0,
// 			bottom: 0,
// 		},
// 		bgColor: "#ffffff",
// 		bg: "rgba(0,0,0,0)",
// 	},
// 	radius: {
// 		enable: false,
// 		show: false,
// 		size: 100,
// 		uniform: true,
// 		lt: 100,
// 		rt: 100,
// 		lb: 100,
// 		rb: 100,
// 	},
// 	blur: {
// 		type: "color",
// 		size: 200,
// 		gradient: {
// 			angle: 0,
// 			colors: ["lightblue", "#FFF", "pink"],
// 		},
// 	},
// 	logo: {
// 		enable: false,
// 		show: false,
// 		auto: true,
// 		name: "nikon",
// 		width: 300,
// 		height: 300,
// 		verticalOffset: 1,
// 		circle: false,
// 		url: "",
// 	},
// 	divider: {
// 		enable: false,
// 		show: false,
// 		color: "#808080",
// 		width: 5,
// 		scale: 1,
// 		margin: 1,
// 	},
// 	shadow: {
// 		show: false,
// 		color: "#000",
// 		size: 100,
// 		x: 0,
// 		y: 0,
// 	},
// 	location: {
// 		...defaultLabelConfig,
// 		enable: false,
// 	},
// 	filter: {
// 		saturation: 100,
// 		brightness: 100,
// 		contrast: 100,
// 		grayscale: 0,
// 		invert: 0,
// 	},
// 	border: {
// 		enable: true,
// 		show: false,
// 		width: 50,
// 		color: "rgb(128,128,128)",
// 	},
// 	margin: {
// 		show: false,
// 		top: 0,
// 		bottom: 0,
// 		left: 0,
// 		right: 0,
// 	},
// 	labels: [],
// 	images: [],
// 	draw: () => {},
// 	beforeDraw: () => {},
// 	afterDraw: () => {},
// };

export const defaultExif = {
	Make: "NIKON CORPORATION",
	Model: "NIKON Z 30",
	Orientation: "Horizontal (normal)",
	XResolution: 300,
	YResolution: 300,
	ResolutionUnit: "inches",
	Software: "Ver.01.11",
	ModifyDate: "2025-03-22T07:03:02.000Z",
	Artist: "WUQZ",
	YCbCrPositioning: 2,
	Copyright: "SHOT_BY_WQZ",
	ExposureTime: 0.0025,
	FNumber: 8,
	ExposureProgram: "Manual",
	ISO: 100,
	SensitivityType: 2,
	RecommendedExposureIndex: 100,
	ExifVersion: "2.3.1",
	DateTimeOriginal: "2025-03-22T07:03:02.000Z",
	CreateDate: "2025-03-22T07:03:02.000Z",
	OffsetTime: "+08:00",
	OffsetTimeOriginal: "+08:00",
	OffsetTimeDigitized: "+08:00",
	ComponentsConfiguration: {
		"0": 1,
		"1": 2,
		"2": 3,
		"3": 0,
	},
	CompressedBitsPerPixel: 4,
	ExposureCompensation: -1,
	MeteringMode: "Pattern",
	LightSource: "Unknown",
	Flash: "Flash did not fire",
	FocalLength: 50,
	SubSecTime: "65",
	SubSecTimeOriginal: "65",
	SubSecTimeDigitized: "65",
	FlashpixVersion: "1.0",
	ColorSpace: 1,
	ExifImageWidth: 5568,
	ExifImageHeight: 3712,
	SensingMethod: "One-chip color area sensor",
	FileSource: "Digital Camera",
	SceneType: "Directly photographed",
	CFAPattern: {
		"0": 2,
		"1": 0,
		"2": 2,
		"3": 0,
		"4": 0,
		"5": 1,
		"6": 1,
		"7": 2,
	},
	CustomRendered: "Custom",
	ExposureMode: "Manual",
	WhiteBalance: "Auto",
	FocalLengthIn35mmFormat: 75,
	SceneCaptureType: "Standard",
	GainControl: "None",
	Contrast: "Normal",
	Saturation: "Normal",
	Sharpness: "High",
	SubjectDistanceRange: "Unknown",
	SerialNumber: "8087759",
	LensInfo: [50, 250, 4.5, 6.3],
	LensMake: "NIKON",
	LensModel: "NIKKOR Z DX 50-250mm f/4.5-6.3 VR",
	LensSerialNumber: "20322022",
	GPSVersionID: "2.3.0.0",
};

export function commonCaculate(config: Config, imgW: number, imgH: number) {
	const {
		global: { paddings: globalPaddings },
		img: { margin: imgMargin },
		watermark: { paddings: watermarkPaddings },
	} = config;

	// 计算实际的画布内边距，以宽度为准
	const canvasPaddings = {
		top: (globalPaddings.top * imgW) / 100,
		bottom: (globalPaddings.bottom * imgW) / 100,
		left: (globalPaddings.left * imgW) / 100,
		right: (globalPaddings.right * imgW) / 100,
	};
	// 计算实际的图片外边距
	const realImgMargin = {
		top: (imgMargin.top * imgH) / 100,
		bottom: (imgMargin.bottom * imgH) / 100,
		left: (imgMargin.left * imgW) / 100,
		right: (imgMargin.right * imgW) / 100,
	};
	// 计算水印实际内边距
	const realWatermarkPaddings = {
		top: (watermarkPaddings.top * imgH) / 100,
		bottom: (watermarkPaddings.bottom * imgH) / 100,
		left: (watermarkPaddings.left * imgW) / 100,
		right: (watermarkPaddings.right * imgW) / 100,
	};

	return {
		canvasPaddings,
		realImgMargin,
		realWatermarkPaddings,
	};
}
